source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec jekyll serve`.

# This is the default theme for new Jekyll sites.
gem "minima"

# The following plugins are automatically loaded by the theme-gem:
#   jekyll-seo-tag, jekyll-sitemap, jekyll-feed, jekyll-include-cache

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "kramdown-parser-gfm", "~> 1.1"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", platforms: [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` for JRuby builds
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]

# Reduce memory usage when building the site
gem "jekyll-commonmark-ghpages", "~> 0.4"

# Optional: Add more plugins as needed
# gem "jekyll-paginate"
# gem "jekyll-gist"
# gem "jekyll-github-metadata"